Fix incomplete documentation for load functions
solidjs/solid-docs pull request #653
Opened 2024-04-06 03:47 UTC by Kerrick

[The `<Router>` component's children include `RouteDefinition`s](https://github.com/solidjs/solid-router?tab=readme-ov-file#router), which [accept a `component` that accepts `RouteSectionProps`](https://github.com/solidjs/solid-router/blob/e773947b85ac78281816e86621a2cdb6735ae95a/src/types.ts#L84-L91). Those components are [passed, alongside `params` etc., `data`](https://github.com/solidjs/solid-router/blob/e773947b85ac78281816e86621a2cdb6735ae95a/src/types.ts#L77-L82). That `data` prop is [the result of calling the `load` function](https://github.com/solidjs/solid-router/blob/e773947b85ac78281816e86621a2cdb6735ae95a/src/routing.ts#L501-L512). This PR documents that prop.

This PR also more-explicitly documents the createAsync + load pattern recommended by @lxsmnsyc [as per this discussion on Discord](https://discord.com/channels/722131463138705510/861229287868858379/1225863092341309661).

2024-05-09 17:42 UTC, LadyBluenotes requested changes
Hi @Kerrick thank you for working on this.

Do you mind making sure that this follows a similar structure to the other reference pages where the table is below most of the content, outside of any methods or functions associated. As an example - https://docs.solidjs.com/reference/components/suspense-list

2024-05-26 10:12 UTC, vincentfretin commented on src/routes/solid-router/reference/load-functions/load.mdx
> +export const loadUser = ({ params, location }) => fetchUser(params.id);
You meant `getUser` instead of `fetchUser` here?

2024-09-21 02:32 UTC, LadyBluenotes commented
Hi @Kerrick ! I was wondering if you were still working on this?

2024-09-21 02:49 UTC, Kerrick commented
> Hi @Kerrick ! I was wondering if you were still working on this?

I am not.

2024-12-16 23:45 UTC, brenelz commented
@LadyBluenotes Can maybe just close this one. Its a bit outdated by using `load` instead of `preload` and `cache` instead of `query`

2024-12-16 23:54 UTC, LadyBluenotes commented
@brenelz thanks for keeping posted on this one!

2024-12-16 23:54 UTC, closed without merging