docs(translation): Add spanish UI translations
solidjs/solid-docs pull request #762
Opened 2024-06-01 00:14 UTC by royeden

Adds _generic_ spanish translations. _Generic_ implies that spanish speakers will understand them, regardless of their regional variant.

This should provide a base for future spanish translations, where regional variants have different words to refer to different concepts (in case that is needed).

* Comment regarding code: If english is the default, and the keys have to match, it could be good to match the `type` of translation dictionaries to match the keys in the english dictionary.

* Notes on translations:
```ts
{
        // This reads like UIs with no effort, with reactive precision. The comma could be ommited.
	"hero.title": "UIs sin esfuerzo, con precisión reactiva.", 
	
	 // Could be a more informal "Empezar ahora"
	"hero.button.primary": "Comenzar ahora",
	
	// This could also be translated as "Derivación de valores", meaning "Value derivation", 
	"main.nav.section.derived.values": "Valores derivados",
	
	 // This is a known colloquial translation for "routing", known as an "americanism" to refer to the "correct" term: "Enrutado".
	 // I've never personally seen "Enrutado" being used in a technological project / education.
	"main.nav.section.routing": "Ruteo",

        // This is another known colloquial translation derived from "render"
	"main.nav.section.rendering": "Renderizado",

        // I feel like translating stores might be a bit cumbersome, due to it being a specific API in the project
	"main.nav.section.stores": "Stores",

        // Same thing with `Solid-Router`.
	"main.nav.section.solid.router": "Solid-Router",
	
	// Reads like "functions for loading"
	"main.nav.section.solid.router.load.functions": "Funciones de carga",
}
```

2024-08-24 04:13 UTC, titoBouzout requested changes

2024-08-24 04:13 UTC, titoBouzout commented on src/i18n/dictionaries/es/ui.ts
> +	"hero.subtitle": "SolidJS es un moderno framework de Javascript para la web de hoy.",
`Solid` Para hacer referencia a Solid en documentos internos (dentro de la comunidad de Solid) 
`SolidJS` para hacer referencia a Solid desde fuera de la comunidad/documentación de Solid. 

`SolidJS` -> `Solid`

2024-08-24 04:13 UTC, titoBouzout commented on src/i18n/dictionaries/es/ui.ts
> +	"hero.subtitle": "SolidJS es un moderno framework de Javascript para la web de hoy.",
Javascript -> JavaScript

2024-08-25 23:23 UTC, royeden commented on src/i18n/dictionaries/es/ui.ts
> +	"hero.subtitle": "SolidJS es un moderno framework de Javascript para la web de hoy.",
Done!

2024-09-24 14:27 UTC, titoBouzout commented
@royeden Thanks Roy for the update! 

I've asked around, and would like to inform you why this has been appearing to take a bit of time. The docs site was made with translations/localizations in mind, but then it was restructured to include SolidStart, SolidRouter and SolidMeta. This caused mayor changes to the localizations' logic, such switching languages between pages of the different subprojects and the like. It's on the works but will require some time to get it done as it was before.

2025-03-07 23:49 UTC, LadyBluenotes commented
I'm going to close this PR as it is quite behind where the current docs are (which is our fault, not yours). If you'd like to continue assisting with the Spanish translations, we'd love to have a conversation about this for the new infra!

2025-03-07 23:49 UTC, closed without merging

2025-03-08 00:59 UTC, royeden commented
@LadyBluenotes no problem, let me know about how this impacts the new infra and I'll go and make the translations :smile:

2025-03-08 01:09 UTC, LadyBluenotes commented
@jer3m01 do you mind providing some insight into how SolidBase will be doing i18n?