Update action.mdx
solidjs/solid-docs pull request #846
Opened 2024-08-15 11:31 UTC by madaxen86

Added documentation for revalidation of cached functions with actions and revalidate helper.

2024-08-21 08:25 UTC, atilafassina requested changes
Thanks for this!! Great work!! 🏆

I made a few minor suggestions, feel free to take them entirely, partially, or reply :)

Looking forward to merge this!

2024-08-21 08:25 UTC, atilafassina commented on src/routes/solid-router/reference/data-apis/action.mdx
> +By default all cached function will be revalidated wether the action does not return or return a "normal" response.
```suggestion
By default all cached functions will be revalidated wether the action does not return or return a "normal" response.
```

2024-08-21 08:25 UTC, atilafassina commented on src/routes/solid-router/reference/data-apis/action.mdx
> +  // ...
It's preffered that snippets are copy-pasteable. And in this case I think the return would be ideal to have. What do you think?

```suggestion
  // ...
  return new  Response("success",  {  status:  200  });
```

2024-08-21 08:25 UTC, atilafassina commented on src/routes/solid-router/reference/data-apis/action.mdx
> +By returning a response with solid router's `json` or `reload` helpers you can pass a key / keys to the revalidate prop as the second argument of solid's router json response helper.  You can either
```suggestion
By returning a response with solid-router's `json` or `reload` helpers you can pass a key / keys to the revalidate prop as the second argument of the json response helper.
You can either pass as `string` directly or use the cached functions `key` or `keyFor` props.

2024-08-21 08:25 UTC, atilafassina commented on src/routes/solid-router/reference/data-apis/action.mdx
> +### No revalidation
Imho, "prevent" seems to convey better the message than simply "no" in this case.

```suggestion
Prevent revalidation
```

2024-08-21 08:25 UTC, atilafassina commented on src/routes/solid-router/reference/data-apis/action.mdx
> +To opt out of any revalidation you can pass any string to revalidate which is not a key of any cached function.
```suggestion
To opt out of any revalidation you can pass any `string` to revalidate which is not a key of any cached function.
```

2024-08-21 08:25 UTC, atilafassina commented on src/routes/solid-router/reference/data-apis/action.mdx
> +  return reload({ revalidate: "nothing" })
```suggestion
  // returns a `json` without revalidating the action.
  return json(`deleted ${id}`,{ revalidate: "nothing" })

  // or reload the route without revalidating the request.
  // return reload({ revalidate: "nothing" })
```

If showing alternatives, I'd propose we point out the differences between them explicitly.
(the wording is just a suggestion, I'm happy if you go with something else)

2024-08-21 08:25 UTC, atilafassina commented on src/routes/solid-router/reference/data-apis/action.mdx
> +This is also great if you want to set your own "refresh" interval e.g. poll data every 30 seconds .
```suggestion
This is also great if you want to set your own "refresh" interval e.g. poll data every 30 seconds.
```

2024-08-21 08:25 UTC, atilafassina commented on src/routes/solid-router/reference/data-apis/action.mdx
> +	...
Use the same formatting as the previous snippets and comment out what isn't valid code.

```suggestion
	// ...
```

2024-08-23 15:26 UTC, madaxen86 commented
Good suggestions.
I've also added the `redirect` helper as an option.

2024-09-17 22:24 UTC, atilafassina approved these changes

2024-09-21 01:26 UTC, merged