add encodeURIComponent to query results report
solidjs/solid-docs pull request #869
Opened 2024-09-06 02:57 UTC by titoBouzout

2024-09-06 04:16 UTC, LadyBluenotes commented
Could you please add a description to explain this or link an issue that this is related to?

2024-09-06 12:11 UTC, titoBouzout commented
Sure, sorry about that. 

When constructing links, the value of the parameters must be url encoded, else the receiver server could see garbled text when using non-english, and/or the text could be cut when using special characters.

For `quack & murci`, the difference between these links
(encoded)
`https://github.com/solidjs/solid-docs-next/issues/new?title=quack%20%26%20murci`
(not encoded)
`https://github.com/solidjs/solid-docs-next/issues/new?title=quack & murci`

when opening the second link, it will display "quack" instead of "quack & murci"

2024-09-17 22:32 UTC, atilafassina requested changes
Awesome!! Just a slight change since the repo moved.

2024-09-17 22:32 UTC, atilafassina commented on src/ui/search.tsx
> +										href={`https://github.com/solidjs/solid-docs-next/issues/new?title=[Search]+Missing+results+for+query+%22${encodeURIComponent(searchTerm())}%22`}
```suggestion
										href={`https://github.com/solidjs/solid-docs/issues/new?title=[Search]+Missing+results+for+query+%22${encodeURIComponent(searchTerm())}%22`}
```

2024-09-17 22:32 UTC, atilafassina approved these changes

2024-09-17 22:33 UTC, merged