WIP: Reduce bundle size
solidjs/solid-docs pull request #906
Opened 2024-09-28 20:44 UTC by brenelz

- [X] I have read the [Contribution guide](https://github.com/solidjs/solid-docs/blob/main/CONTRIBUTING.md)
- [X] This PR references an issue (except for typos, broken links, or other minor problems)

### Description(required)
Playing around a bit with bundle size and lighthouse scores on the docs. I wondered if I could improve things by keeping our syntax highligher(shiki) on the server.  I will do a bit of testing to see if it actually improves things

### Related issues & labels

2024-10-10 21:50 UTC, brenelz commented
@atilafassina do you have any thoughts on this? Is it a good approach to reduce bundle size or do we want the highlighter on the client?

2024-10-10 21:55 UTC, atilafassina commented
> @atilafassina do you have any thoughts on this? Is it a good approach to reduce bundle size or do we want the highlighter on the client?

the highlighter on the client was a quick-and-dirty thing that was hacked around for the PoC stage which I never had time to get back to. So I totally appreciate the time and effort you're putting into this!!

2024-10-25 20:01 UTC, brenelz commented
Just re commenting here for visibility. Is this worth investing some time in? I think its mostly there

2024-10-28 14:14 UTC, LadyBluenotes commented
> Just re commenting here for visibility. Is this worth investing some time in? I think its mostly there

I'd say this is worth investing time in, especially if you have an idea of how to do it and it isn't too complicated

2024-11-24 08:02 UTC, atilafassina requested changes
small nit! 🏆

2024-11-24 08:02 UTC, atilafassina commented on src/ui/layout/hero-code-snippet.tsx
> +import { cache, createAsync } from "@solidjs/router";
```suggestion
import { query, createAsync } from "@solidjs/router";
```

2024-11-24 08:02 UTC, atilafassina commented on src/ui/layout/hero-code-snippet.tsx
> +const renderCode = cache(async () => {
```suggestion
const renderCode = query(async () => {
```

2024-11-24 16:41 UTC, brenelz commented on src/ui/layout/hero-code-snippet.tsx
> +import { cache, createAsync } from "@solidjs/router";
Looks like we are on an older version of the router. Should i upgrade the router or leave it as is?

2024-12-03 17:42 UTC, atilafassina approved these changes

2024-12-03 17:42 UTC, atilafassina commented on src/ui/layout/hero-code-snippet.tsx
> +import { cache, createAsync } from "@solidjs/router";
oh really?! I thought that was updated already.. nevermind then

2024-12-03 17:43 UTC, merged