Add note about TypeScript requiring types for namespaced attributes
solidjs/solid-docs pull request #954
Opened 2024-11-14 18:41 UTC by titoBouzout

- [x ] I have read the [Contribution guide](https://github.com/solidjs/solid-docs/blob/main/CONTRIBUTING.md)
- [ ] This PR references an issue (except for typos, broken links, or other minor problems)

### Description(required)

Someone made a note on discord that for example `prop:scrollTop` gives a type error, and asked if that was a bug.  Related docs page https://docs.solidjs.com/reference/jsx-attributes/prop

I understood the expectation, given that there is no indication that the typings for such a prop must be provided by the user. I understand we do not want to include types on each page and have a special page for types instead. So I'm including a note on each special namespaced attributes page indicating that the types must be provided and linking to the examples given in the TypeScript page

I'm not that sure about the format of the note as in "Note: text", or could be a callout but maybe It's too much, maybe we can bold the "Note" part? 

### Related issues & labels

- Closes #
- Suggested label(s) (optional):

2024-11-22 14:39 UTC, atilafassina requested changes
Small nits about using the built components for highlighting/callout

2024-11-22 14:39 UTC, atilafassina commented on src/routes/reference/jsx-attributes/bool.mdx
> +Note: Type definitions are required when using TypeScript. See the [TypeScript](/configuration/typescript#forcing-properties-and-custom-attributes) page for examples.
You can use the Callout component

```ts
<Callout type="info" title="Strong-Typing Custom Properties">...</Callout>
```

2024-11-22 14:39 UTC, atilafassina commented on src/routes/reference/jsx-attributes/prop.mdx
> +Note: Type definitions are required when using TypeScript. See the [TypeScript](/configuration/typescript#forcing-properties-and-custom-attributes) page for examples.
You can use the Callout component

```ts
<Callout type="info" title="Strong-Typing Custom Properties">...</Callout>
```

2024-11-28 00:59 UTC, titoBouzout commented
Thanks @atilafassina changes made, using a `Callout` for the "Note:"

2024-12-01 02:07 UTC, LadyBluenotes approved these changes

2024-12-01 08:17 UTC, atilafassina approved these changes

2024-12-01 08:17 UTC, merged