document setter function passing previous value
solidjs/solid-docs pull request #961
Opened 2024-11-24 02:55 UTC by brenelz

- [X] I have read the [Contribution guide](https://github.com/solidjs/solid-docs/blob/main/CONTRIBUTING.md)
- [X] This PR references an issue (except for typos, broken links, or other minor problems)

### Description(required)
Document setter that passes previous value

### Related issues & labels

- Closes #909

2024-11-24 04:40 UTC, LadyBluenotes requested changes

2024-11-24 04:40 UTC, LadyBluenotes commented on src/routes/concepts/signals.mdx
> +The setter function also can take a function that passes the previous value.
```suggestion
The setter function can also take a function that passes the previous value.
```

2024-11-24 08:09 UTC, atilafassina approved these changes

2024-11-26 02:56 UTC, LadyBluenotes approved these changes

2024-11-26 02:56 UTC, merged